import = [".config/alacritty/dracula.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Bold"

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[scrolling]
history = 100000

[selection]
save_to_clipboard = true
